#Each new term in the Fibonacci sequence is generated by adding 
# the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.

# Find all Fibonacci sequence numbers up to 4000000
# Sum even terms

sum = 0 
fib = [1, 2]
for i in range(10000):
    fib.append(fib[i] + fib[i+1])
    if fib[-1] > 4000000:
        fib.pop(-1)
        break
#print(fib)

for i in fib:
    if i % 2 == 0:
        sum += i
print(sum)
